### ISSUE TITLE
rails 3.1 issues

### ISSUE THREAD

**Issue by krtschmr** [RubyMoney/money-rails#504]
anybody having 3.1 issues?
either this gem nor the regular money gem works in our 3.1 application. as soon we add it to gemfile it's failing

> 
> /home/tim/.rvm/gems/ruby-2.1.6/gems/bundler-1.13.3/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'money-rails'. (Bundler::GemRequireError)
> Gem Load Error is: undefined method `[]' for nil:NilClass
> Backtrace for gem load error is:
> /home/tim/.rvm/gems/ruby-2.1.6/gems/money-6.9.0/lib/money/currency.rb:436:in `initialize_data!'
> /home/tim/.rvm/gems/ruby-2.1.6/gems/money-6.9.0/lib/money/currency.rb:264:in `initialize'
> /home/tim/.rvm/gems/ruby-2.1.6/gems/money-6.9.0/lib/money/currency.rb:44:in `new'
> /home/tim/.rvm/gems/ruby-2.1.6/gems/money-6.9.0/lib/money/currency.rb:44:in `block in new'
> /home/tim/.rvm/gems/ruby-2.1.6/gems/money-6.9.0/lib/money/currency.rb:44:in `synchronize'
> /home/tim/.rvm/gems/ruby-2.1.6/gems/money-6.9.0/lib/money/currency.rb:44:in `new'
> /home/tim/.rvm/gems/ruby-2.1.6/gems/money-6.9.0/lib/money/money.rb:149:in `setup_defaults'
> /home/tim/.rvm/gems/ruby-2.1.6/gems/money-6.9.0/lib/money/money.rb:168:in `<class:Money>'
> /home/tim/.rvm/gems/ruby-2.1.6/gems/money-6.9.0/lib/money/money.rb:17:in `<top (required)>'
> /home/tim/.rvm/gems/ruby-2.1.6/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
> /home/tim/.rvm/gems/ruby-2.1.6/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
> /home/tim/.rvm/gems/ruby-2.1.6/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
> /home/tim/.rvm/gems/ruby-2.1.6/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
> /home/tim/.rvm/gems/ruby-2.1.6/gems/money-6.9.0/lib/money.rb:6:in `<top (required)>'
>

**Comment by igneus** [comment]
I have created a fresh Rails 3.1.12 application, included the money-rails gem, no problems so far.

What is your exact Rails version?
Would it be possible to share the complete contents of your `Gemfile`?

**Comment by krtschmr** [comment]
allright, figured it out.

we use rails 3.22 and shitload of gems. 
i can't figure out *which* gem kills it, but i found out, if i put `gem 'money'` on top of my gemfile it simply works. if i put it at the end, it breaks.

**Comment by antstorm** [comment]
@krtschmr in case you've got some spare time it'd be really good to figure out which gem `money` clashes with. Chances are others might have this problem as well.
