### ISSUE TITLE
not working with Rails 3.0.X

### ISSUE THREAD

**Issue by shakerlxxv** [RubyMoney/money-rails#22]
Hi,
I'm trying to use this gem with a Rails 3.0.X application. Bundler installed v ( 0.4.0 ) originally against rails v ( 3.0.3 ) and I get the following exception when trying to load a model class using the 'monetize' method:

```
ree-1.8.7-2011.03 :001 > f = Fee.new
NoMethodError: undefined method `attribute_names' for #<Class:0x1e61f58>
        from /home/bshaver/.rvm/gems/ree-1.8.7-2011.03@handyworks-r3/gems/activerecord-3.0.5/lib/active_record/base.rb:1008:in `method_missing'
        from /home/bshaver/.rvm/gems/ree-1.8.7-2011.03@handyworks-r3/gems/money-rails-0.4.0/lib/money-rails/active_record/monetizable.rb:50:in `monetize'
        from /home/bshaver/Documents/Projects/Schram/handyworks-r3a/app/models/fee.rb:2
        from /home/bshaver/.rvm/gems/ree-1.8.7-2011.03@handyworks-r3/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:454:in `load'
```

I tried changing Ruby versions to MRI 1.9.3, also tried updating to Rails v (3.0.5) and get the same results.

I can reproduce the error in a brand new application using a single model and only adding the money-rails gem / monetize method.

However, when I do the same with either Rails 3.1.X or Rails 3.2.X it works as expected. So it definitely seems to be a compatibility issue with Rails 3.0 versions.

I'm wondering if either there's an older version that would be compatible with Rails 3.0.X, and if so perhaps there's something that can be modified in the gem packaging to encourage bundler to install a compatible version.

Worst case, then I'd suggest listing Rails 3.1 as a minimum requirement for the gem.
